(use-modules (guix packages)
             (guix build-system go)
             (gnu packages golang)
             (guix git-download)
             ((guix licenses) #:prefix license:))

(define-public hugo
  (package
    (name "hugo")
    (version "0.80.0")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/gohugoio/hugo")
             (commit (string-append "v" version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "0xs9y5lj0mya6ag625x8j91mn9l9r13gxaqxyvl1fl40y2yjz1zm"))))
    (build-system go-build-system)
    (arguments
     `(#:unpack-path "github.com/gohugoio"))
    (native-inputs
     `(("go-github-com-burntsushi-locker" ,go-github-com-burntsushi-locker)
       ("go-github-com-burntsushi-toml" ,go-github-com-burntsushi-toml)
       ("go-github-com-puerkitobio-purell" ,go-github-com-puerkitobio-purell)
       ("go-github-com-puerkitobio-urlesc" ,go-github-com-puerkitobio-urlesc)
       ("go-github-com-alecthomas-chroma" ,go-github-com-alecthomas-chroma)
       ("go-github-com-alecthomas-repr" ,go-github-com-alecthomas-repr)
       ("go-github-com-armon-go-radix" ,go-github-com-armon-go-radix)
       ("go-github-com-aws-aws-sdk-go" ,go-github-com-aws-aws-sdk-go)
       ("go-github-com-bep-debounce" ,go-github-com-bep-debounce)
       ("go-github-com-bep-gitmap" ,go-github-com-bep-gitmap)
       ("go-github-com-bep-godartsass" ,go-github-com-bep-godartsass)
       ("go-github-com-bep-golibsass" ,go-github-com-bep-golibsass)
       ("go-github-com-bep-tmc" ,go-github-com-bep-tmc)
       ("go-github-com-cli-safeexec" ,go-github-com-cli-safeexec)
       ("go-github-com-disintegration-gift" ,go-github-com-disintegration-gift)
       ("go-github-com-dlclark-regexp2" ,go-github-com-dlclark-regexp2)
       ("go-github-com-dustin-go-humanize" ,go-github-com-dustin-go-humanize)
       ("go-github-com-evanw-esbuild" ,go-github-com-evanw-esbuild)
       ("go-github-com-fortytw2-leaktest" ,go-github-com-fortytw2-leaktest)
       ("go-github-com-frankban-quicktest" ,go-github-com-frankban-quicktest)
       ("go-github-com-fsnotify-fsnotify" ,go-github-com-fsnotify-fsnotify)
       ("go-github-com-getkin-kin-openapi" ,go-github-com-getkin-kin-openapi)
       ("go-github-com-ghodss-yaml" ,go-github-com-ghodss-yaml)
       ("go-github-com-gobwas-glob" ,go-github-com-gobwas-glob)
       ("go-github-com-gohugoio-testmodbuilder-mods" ,go-github-com-gohugoio-testmodbuilder-mods)
       ("go-github-com-google-go-cmp" ,go-github-com-google-go-cmp)
       ("go-github-com-gorilla-websocket" ,go-github-com-gorilla-websocket)
       ("go-github-com-jdkato-prose" ,go-github-com-jdkato-prose)
       ("go-github-com-kylelemons-godebug" ,go-github-com-kylelemons-godebug)
       ("go-github-com-kyokomi-emoji" ,go-github-com-kyokomi-emoji)
       ("go-github-com-magefile-mage" ,go-github-com-magefile-mage)
       ("go-github-com-markbates-inflect" ,go-github-com-markbates-inflect)
       ("go-github-com-mattn-go-isatty" ,go-github-com-mattn-go-isatty)
       ("go-github-com-miekg-mmark" ,go-github-com-miekg-mmark)
       ("go-github-com-mitchellh-hashstructure" ,go-github-com-mitchellh-hashstructure)
       ("go-github-com-mitchellh-mapstructure" ,go-github-com-mitchellh-mapstructure)
       ("go-github-com-muesli-smartcrop" ,go-github-com-muesli-smartcrop)
       ("go-github-com-nfnt-resize" ,go-github-com-nfnt-resize)
       ("go-github-com-nicksnyder-go-i18n" ,go-github-com-nicksnyder-go-i18n)
       ("go-github-com-niklasfasching-go-org" ,go-github-com-niklasfasching-go-org)
       ("go-github-com-olekukonko-tablewriter" ,go-github-com-olekukonko-tablewriter)
       ("go-github-com-pelletier-go-toml" ,go-github-com-pelletier-go-toml)
       ("go-github-com-pkg-errors" ,go-github-com-pkg-errors)
       ("go-github-com-rogpeppe-go-internal" ,go-github-com-rogpeppe-go-internal)
       ("go-github-com-russross-blackfriday" ,go-github-com-russross-blackfriday)
       ("go-github-com-rwcarlsen-goexif" ,go-github-com-rwcarlsen-goexif)
       ("go-github-com-sanity-io-litter" ,go-github-com-sanity-io-litter)
       ("go-github-com-spf13-afero" ,go-github-com-spf13-afero)
       ("go-github-com-spf13-cast" ,go-github-com-spf13-cast)
       ("go-github-com-spf13-cobra" ,go-github-com-spf13-cobra)
       ("go-github-com-spf13-fsync" ,go-github-com-spf13-fsync)
       ("go-github-com-spf13-jwalterweatherman" ,go-github-com-spf13-jwalterweatherman)
       ("go-github-com-spf13-pflag" ,go-github-com-spf13-pflag)
       ("go-github-com-spf13-viper" ,go-github-com-spf13-viper)
       ("go-github-com-tdewolff-minify" ,go-github-com-tdewolff-minify)
       ("go-github-com-yuin-goldmark" ,go-github-com-yuin-goldmark)
       ("go-github-com-yuin-goldmark-highlighting" ,go-github-com-yuin-goldmark-highlighting)))
    (home-page "https://github.com/gohugoio/hugo")
    (synopsis "Fast web framework for bulding websites")
    (description "")
    (license license:asl2.0)))

hugo
