(use-modules (guix packages)
             (guix build-system gnu)
             (guix download)
             (gnu packages algebra)
             ((guix licenses) #:prefix license:))

(define-public skymaker
  (package
    (name "skymaker")
    (version "3.10.5")
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://www.astromatic.net/download/"
                           name "/" name "-" version ".tar.gz"))
       (sha256
        (base32 "03zvx7c89plp9559niqv5532r233kza3ir992rg3nxjksqmrqvx1"))))
    (build-system gnu-build-system)
    (arguments
     `(#:configure-flags
       (list
        (string-append
         "--with-fftw-libdir=" (assoc-ref %build-inputs "fftw") "/lib")
        (string-append
         "--with-fftw-incdir=" (assoc-ref %build-inputs "fftw") "/include"))))
    (inputs
     `(("fftw" ,fftwf)))
    (home-page "https://www.astromatic.net/software/skymaker")
    (synopsis "Image simulation")
    (description
     "SkyMaker is a program that simulates astronomical images. It accepts
object lists in ASCII generated by the Stuff program to produce realistic
astronomical fields. SkyMaker is part of the EFIGI
(https://www.astromatic.net/projects/efigi) development project.")
    (license license:gpl3+)))

skymaker
