#+title: 20230911234650_letter

Hi Guix!

The end of August Astronomy related packages udpates and new packages. Hopw QA will pick green them
up soon :)

* Updates
- date-time :: 20230905T163102+0100
- commit :: 8d19ff23052bffb1c43f0d39f543eb0b1e363074
- issues :: https://issues.guix.gnu.org/65814
- quick [16/16][100%]
  - [X] libxisf :: would be upgraded from 0.2.8 to 0.2.9.
  - [X] python-astropy-healpix :: would be upgraded from 0.7 to 1.0.0.
  - [X] python-astropy :: would be upgraded from 5.3.1 to 5.3.2
  - [X] python-bayesicfitting :: would be upgraded from 3.1.1 to 3.2.0
  - [X] python-cdflib :: would be upgraded from 1.0.5 to 1.1.0.
  - [X] python-crds :: would be upgraded from 11.17.0 to 11.17.4.
  - [X] python-fitsio :: would be upgraded from 1.1.10 to 1.2.0
  - [X] python-jwst :: would be upgraded from 1.10.2 to 1.11.4
  - [X] python-photutils :: would be upgraded from 1.7.0 to 1.9.0
  - [X] python-pyvo :: would be upgraded from 1.4.1 to 1.4.2
  - [X] python-rad :: would be upgraded from 0.15.0 to 0.17.1
  - [X] python-roman-datamodels :: would be upgraded from 0.15.0 to 0.17.1
  - [X] python-stdatamodels :: would be upgraded from 1.7.1 to 1.8.0
  - [X] python-sunpy :: Enable more tests.
  - [X] python-tslearn :: would be upgraded from 0.6.1 to 0.6.2
  - [X] splash :: would be upgraded from 3.8.2 to 3.8.4.
- complex [0/8][0%]
  - [ ] python-asdf :: would be upgraded from 2.15.0 to 2.15.1. Requires lower version of
    python-jsonschema which and also contain vendorized version which breaks all tests now,
    https://github.com/asdf-format/asdf-standard/releases/tag/1.0.3
  - [ ] cfitsio :: would be upgraded from 4.2.0 to 4.3.0. Building the following 22 packages would
    ensure 66 dependent packages are rebuilt: alfa@2.2 splash@3.8.2 sextractor@2.28.0 imppg@0.6.5
    stellarium@23.2 python-fitsio@1.1.10 glnemo2@1.21.0 siril@1.0.6 python-tslearn@0.6.1
    python-regions@0.7 python-jwst@1.10.2 python-astroalign@2.4.2 python-sunpy@5.0.0
    python-poliastro@0.17.0 julia-wcs@0.6.2 phd2@2.6.11 gnuastro@0.20 aoflagger@3.3.0 swarp@2.41.5
    julia-fitsio@0.17.0 gwenview@23.04.3 labplot@2.9.0.
    Need more love with dependents as some of them failed to build.
  - [ ] python-hvpy :: would be upgraded from 1.0.1 to 1.1.0. Requires more fresh version of
    python-pydantic, which depends on python-pydantic-core which require brand new Rust based
    package.
  - [ ] python-spherical-geometry :: would be upgraded from 1.2.22 to 1.2.23. Can't be updated to
    the latest see: https://github.com/spacetelescope/spherical_geometry/issues/227
  - [ ] aoflagger :: would be upgraded from 3.2.0 to 3.3.0. Build failerur, more work requried.
  - [ ] casacore :: would be upgraded from 3.4.0 to 3.5.0. Build failerur, more work requried.
  - [ ] indi :: would be upgraded from 1.9.9 to 2.0.3. stellarium failing.
  - [ ] libpasastro :: would be upgraded from 1.4.0-1.e3c218d to 1.4.1. Full package reformat is
    requried.

* New packages
- [PATCH] gnu: Add python-casa-formats-io: https://issues.guix.gnu.org/65571
- [PATCH] gnu: Add WCSTools: https://issues.guix.gnu.org/65880
