# -*- mode: org; org-html-head-include-scripts: nil; -*-
#+title: FFAB - Guix channel
/FFAB :: Flock Full of Aleatory Burden/

#+begin_src markdown
[![builds.sr.ht status](https://builds.sr.ht/~hellseher/ffab.svg)](https://builds.sr.ht/~hellseher/ffab?)
#+end_src

This repository contains packaging process and patches contributed to <guix-patches@gnu.org>. It
also can be used as stand alone Guix channel.

The main target is to collect packages related to Astronomy, Astrophysics and group of languages
such as *Common Lisp*, *Golan* and *Python*.

~master~ branch contains of packages passed lint and build procedure and is intended to be save to
use all the time, ~wip-~ branches might be broken on some stage.

* Project structure and layout
Layout follows Guix upstream.

#+BEGIN_SRC sh :results value org :results output replace :exports results
tree  -d ../
#+end_src

#+RESULTS:
#+begin_src org
../
├── etc
├── ffab
│   ├── guix
│   │   ├── build-system
│   │   └── import
│   └── packages
│       └── patches
├── org
├── patches
├── scripts
└── tmp

11 directories
#+end_src

- issues.org :: Tracks all sent patches to <guix-patches@gnu.org>
- TODO.md :: Generated report from packaging process in ~org/~ directory.
- Makefile :: Contains CI aware lint and build targets with convenient tooling for local build.

#+BEGIN_SRC sh :results value org :results output replace :exports results
cd ../
make list
#+end_src

#+RESULTS:
#+begin_src org
:guix-commit 4a34da845ed91821d38ba8a9b65ad650dd7488d1
:accepted 118
:pending 165

:astronomy 34
:golang 41
:lisp 42
:python 13

:date Sun 6 Nov 23:19:10 GMT 2022
#+end_src

* Installation
All examples are based on assumptions that ~guix~ is the main system or available as package
manager.

** Use as channel
~/.config/guix/channels.scm~
#+begin_src scheme
(cons* (channel
        (name 'ffab)
        ;; Mirror https://github.com/Hellseher/guix-channel
        (url "https://git.sr.ht/~hellseher/ffab"))
       %default-channels)
 #+end_src

** Use as build/install source
#+begin_example
~$ git clone https://git.sr.ht/~hellseher/ffab
~$ cd ffab
~$ guix build -L . python-sunpy
#+end_example

* References
- Guix Git  :: https://git.savannah.gnu.org/cgit/guix.git Read only git repository hosted at Savanha.
- Guix CI ::
  - https://ci.guix.gnu.org Main CI and substitute and substitute server
  - https://bordeaux.guix.gnu.org/ Secondary substitute server
- Guix HPC :: http://hpc.guix.info/ Reproducible software deployment for high-performance computing.
- Guix Data Service :: https://data.guix.gnu.org/
- Guix QA Service :: https://qa.guix.gnu.org/

** Guix channels
- https://github.com/flatwhatson/guix-channel
- nonguix :: Guix channel for packages that can't be included upstream. Please do NOT promote or
  refer to this repository on any official Guix communication channels.
  https://gitlab.com/nonguix/nonguix
- guixrus :: Curated collection of packages with goal to promote them to upastream
  https://sr.ht/~whereiseveryone/guixrus/
- Guix Gaming Channels :: A collection of gaming-oriented channels for Guix
  https://gitlab.com/guix-gaming-channels
- Guix Science :: Free scientific packages for GNU Guix https://github.com/guix-science/guix-science
  and non-free scientific packages for GNU Guix https://github.com/guix-science/guix-science-nonfree
- Emacs channel :: Guix channel for automatically generated emacs packages
  https://github.com/babariviere/guix-emacs
** etc
- https://github.com/UMCUGenetics/guix-additions
- https://github.com/ryanprior/guix-packages
- https://github.com/BIMSBbioinfo/guix-bimsb
- https://github.com/techenthusiastsorg/awesome-guix
