(define-module (ffab packages c)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix git-download)
  #:use-module (gnu packages autotools)
  #:use-module (guix packages)
  #:use-module (gnu packages check)
  #:use-module (gnu packages valgrind)
  #:use-module (guix build-system gnu)
  #:use-module (gnu packages))
