(define-module (ffab packages game-development)
  #:use-module (ffab packages lisp-xyz)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages lisp)
  #:use-module (gnu packages lisp-xyz)
  #:use-module (guix build-system asdf)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix packages))

(define-public sbcl-virality
  (let ((commit "4b4d37b3236d3b838dabe7ca7851487366bb8a4b")
        (revision "1"))
    (package
      (name "sbcl-virality")
      (version (git-version "1.0.0" revision commit))
      (source
       (origin
         (method git-fetch)
         (uri (git-reference
               (url "https://github.com/bufferswap/ViralityEngine")
               (commit commit)))
         (file-name (git-file-name "virality" version))
         (sha256
          (base32 "13d7nwh9dfx4pwzxqidlxgif0ww46j9bqyg1yb3sw9sxgcvms87h"))))
      (build-system asdf-build-system/sbcl)
      (inputs
       `(("3b-bmfont" ,sbcl-3b-bmfont)
         ("babel" ,sbcl-babel)
         ("cl-cpus" ,sbcl-cl-cpus)
         ("cl-graph" ,sbcl-graph)
         ("cl-opengl" ,sbcl-cl-opengl)
         ("cl-ppcre" ,sbcl-cl-ppcre)
         ("cl-slug" ,sbcl-cl-slug)
         ("closer-mop" ,sbcl-closer-mop)
         ("fast-io" ,sbcl-fast-io)
         ("global-vars" ,sbcl-global-vars)
         ("jsown" ,sbcl-jsown)
         ("lparallel" ,sbcl-lparallel)
         ("golden-utils" ,sbcl-golden-utils)
         ("origin" ,sbcl-origin)
         ("shadow" ,sbcl-shadow)
         ("umbra" ,sbcl-umbra)
         ("pngload" ,sbcl-pngload)
         ("printv" ,sbcl-printv)
         ("queues" ,sbcl-queues)
         ("sdl2" ,sbcl-sdl2)
         ("split-sequence" ,sbcl-split-sequence)
         ("static-vectors" ,sbcl-static-vectors)
         ("trivial-features" ,sbcl-trivial-features)))
      (home-page "https://github.com/bufferswap/ViralityEngine")
      (synopsis "Component-based game engine written in Common Lisp")
      (description "")
      (license license:expat))))
